workspace:
  base: /go
  path: src/qnmock
pipeline:
   backend:
     pull: true
     image: golang:1.13
     environment:
       - GO111MODULE=on
       - GOPROXY=https://goproxy.cn
     commands:
       - make fmt-check
       - make vet
       - go test ./...
       - make
